-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.10-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for iatireference
CREATE DATABASE IF NOT EXISTS `iatireference` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */;
USE `iatireference`;

-- Dumping structure for table iatireference.ref-country-classification
CREATE TABLE IF NOT EXISTS `ref-country-classification` (
  `ISOA2` char(2) DEFAULT NULL,
  `ISOA3` char(3) DEFAULT NULL,
  `UNCountry` varchar(50) DEFAULT NULL,
  `UNLDC` char(3) DEFAULT NULL,
  `Income` varchar(25) DEFAULT NULL,
  `Region` varchar(35) DEFAULT NULL,
  `FragileState` char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table iatireference.ref-country-classification: ~239 rows (approximately)
DELETE FROM `ref-country-classification`;
/*!40000 ALTER TABLE `ref-country-classification` DISABLE KEYS */;
INSERT INTO `ref-country-classification` (`ISOA2`, `ISOA3`, `UNCountry`, `UNLDC`, `Income`, `Region`, `FragileState`) VALUES
	('AF', 'AFG', 'Afghanistan', 'LDC', 'Low income', 'South Asia', 'Y'),
	('AX', 'ALA', 'Aland Islands', '', '', '', NULL),
	('AL', 'ALB', 'Albania', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('DZ', 'DZA', 'Algeria', '', 'Upper middle income', 'Middle East & North Africa', NULL),
	('AS', 'ASM', 'American Samoa', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('AD', 'AND', 'Andorra', '', '', '', NULL),
	('AO', 'AGO', 'Angola', 'LDC', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('AI', 'AIA', 'Anguilla', '', '', '', NULL),
	('AG', 'ATG', 'Antigua and Barbuda', '', 'High income', 'Latin America & Caribbean', NULL),
	('AR', 'ARG', 'Argentina', '', 'High income', 'Latin America & Caribbean', NULL),
	('AM', 'ARM', 'Armenia', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('AW', 'ABW', 'Aruba', '', 'High income', 'Latin America & Caribbean', NULL),
	('AU', 'AUS', 'Australia', '', 'High income', 'East Asia & Pacific', NULL),
	('AT', 'AUT', 'Austria', '', 'High income', 'Europe & Central Asia', NULL),
	('AZ', 'AZE', 'Azerbaijan', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('BS', 'BHS', 'Bahamas', '', 'High income', 'Latin America & Caribbean', NULL),
	('BH', 'BHR', 'Bahrain', '', 'High income', 'Middle East & North Africa', NULL),
	('BD', 'BGD', 'Bangladesh', 'LDC', 'Lower middle income', 'South Asia', NULL),
	('BB', 'BRB', 'Barbados', '', 'High income', 'Latin America & Caribbean', NULL),
	('BY', 'BLR', 'Belarus', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('BE', 'BEL', 'Belgium', '', 'High income', 'Europe & Central Asia', NULL),
	('BZ', 'BLZ', 'Belize', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('BJ', 'BEN', 'Benin', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('BM', 'BMU', 'Bermuda', '', 'High income', 'North America', NULL),
	('BT', 'BTN', 'Bhutan', 'LDC', 'Lower middle income', 'South Asia', NULL),
	('BO', 'BOL', 'Bolivia (Plurinational State of)', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('BQ', 'BES', 'Bonaire, Saint Eustatius and Saba', '', '', '', NULL),
	('BA', 'BIH', 'Bosnia and Herzegovina', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('BW', 'BWA', 'Botswana', '', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('BR', 'BRA', 'Brazil', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('VG', 'VGB', 'British Virgin Islands', '', '', '', NULL),
	('BN', 'BRN', 'Brunei Darussalam', '', 'High income', 'East Asia & Pacific', NULL),
	('BG', 'BGR', 'Bulgaria', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('BF', 'BFA', 'Burkina Faso', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('BI', 'BDI', 'Burundi', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('KH', 'KHM', 'Cambodia', 'LDC', 'Low income', 'East Asia & Pacific', NULL),
	('CM', 'CMR', 'Cameroon', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('CA', 'CAN', 'Canada', '', 'High income', 'North America', NULL),
	('CV', 'CPV', 'Cape Verde', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('KY', 'CYM', 'Cayman Islands', '', 'High income', 'Latin America & Caribbean', NULL),
	('CF', 'CAF', 'Central African Republic', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('TD', 'TCD', 'Chad', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('CL', 'CHL', 'Chile', '', 'High income', 'Latin America & Caribbean', NULL),
	('CN', 'CHN', 'China', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('HK', 'HKG', 'China, Hong Kong Special Administrative Region', '', 'High income', 'East Asia & Pacific', NULL),
	('MO', 'MAC', 'China, Macao Special Administrative Region', '', 'High income', 'East Asia & Pacific', NULL),
	('CO', 'COL', 'Colombia', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('KM', 'COM', 'Comoros', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('CG', 'COG', 'Congo', '', 'Lower middle income', 'Sub-Saharan Africa', ''),
	('CK', 'COK', 'Cook Islands', '', '', '', NULL),
	('CR', 'CRI', 'Costa Rica', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('CI', 'CIV', 'Cote d\'Ivoire', '', 'Lower middle income', 'Sub-Saharan Africa', 'Y'),
	('HR', 'HRV', 'Croatia', '', 'High income', 'Europe & Central Asia', NULL),
	('CU', 'CUB', 'Cuba', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('CW', 'CUW', 'Curacao', '', 'High income', 'Latin America & Caribbean', NULL),
	('CY', 'CYP', 'Cyprus', '', 'High income', 'Europe & Central Asia', NULL),
	('CZ', 'CZE', 'Czech Republic', '', 'High income', 'Europe & Central Asia', NULL),
	('KP', 'PRK', 'Democratic People\'s Republic of Korea', '', 'Low income', 'East Asia & Pacific', NULL),
	('CD', 'COD', 'Democratic Republic of the Congo', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('DK', 'DNK', 'Denmark', '', 'High income', 'Europe & Central Asia', NULL),
	('DJ', 'DJI', 'Djibouti', 'LDC', 'Lower middle income', 'Middle East & North Africa', 'Y'),
	('DM', 'DMA', 'Dominica', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('DO', 'DOM', 'Dominican Republic', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('EC', 'ECU', 'Ecuador', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('EG', 'EGY', 'Egypt', '', 'Lower middle income', 'Middle East & North Africa', NULL),
	('SV', 'SLV', 'El Salvador', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('GQ', 'GNQ', 'Equatorial Guinea', 'LDC', 'High income', 'Sub-Saharan Africa', NULL),
	('ER', 'ERI', 'Eritrea', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('EE', 'EST', 'Estonia', '', 'High income', 'Europe & Central Asia', NULL),
	('ET', 'ETH', 'Ethiopia', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('FO', 'FRO', 'Faeroe Islands', '', 'High income', 'Europe & Central Asia', NULL),
	('FK', 'FLK', 'Falkland Islands (Malvinas)', '', '', '', NULL),
	('FJ', 'FJI', 'Fiji', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('FI', 'FIN', 'Finland', '', 'High income', 'Europe & Central Asia', NULL),
	('FR', 'FRA', 'France', '', 'High income', 'Europe & Central Asia', NULL),
	('GF', 'GUF', 'French Guiana', '', '', '', NULL),
	('PF', 'PYF', 'French Polynesia', '', 'High income', 'East Asia & Pacific', NULL),
	('GA', 'GAB', 'Gabon', '', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('GM', 'GMB', 'Gambia', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('GE', 'GEO', 'Georgia', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('DE', 'DEU', 'Germany', '', 'High income', 'Europe & Central Asia', NULL),
	('GH', 'GHA', 'Ghana', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('GI', 'GIB', 'Gibraltar', '', '', '', NULL),
	('GR', 'GRC', 'Greece', '', 'High income', 'Europe & Central Asia', NULL),
	('GL', 'GRL', 'Greenland', '', 'High income', 'Europe & Central Asia', NULL),
	('GD', 'GRD', 'Grenada', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('GP', 'GLP', 'Guadeloupe', '', '', '', NULL),
	('GU', 'GUM', 'Guam', '', 'High income', 'East Asia & Pacific', NULL),
	('GT', 'GTM', 'Guatemala', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('GG', 'GGY', 'Guernsey', '', '', '', NULL),
	('GN', 'GIN', 'Guinea', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('GW', 'GNB', 'Guinea-Bissau', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('GY', 'GUY', 'Guyana', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('HT', 'HTI', 'Haiti', '', 'Low income', 'Latin America & Caribbean', 'Y'),
	('VA', 'VAT', 'Holy See', '', '', '', NULL),
	('HN', 'HND', 'Honduras', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('HU', 'HUN', 'Hungary', '', 'High income', 'Europe & Central Asia', NULL),
	('IS', 'ISL', 'Iceland', '', 'High income', 'Europe & Central Asia', NULL),
	('IN', 'IND', 'India', '', 'Lower middle income', 'South Asia', NULL),
	('ID', 'IDN', 'Indonesia', '', 'Lower middle income', 'East Asia & Pacific', NULL),
	('IR', 'IRN', 'Iran (Islamic Republic of)', '', 'Upper middle income', 'Middle East & North Africa', NULL),
	('IQ', 'IRQ', 'Iraq', '', 'Upper middle income', 'Middle East & North Africa', 'Y'),
	('IE', 'IRL', 'Ireland', '', 'High income', 'Europe & Central Asia', NULL),
	('IM', 'IMN', 'Isle of Man', '', '', '', NULL),
	('IL', 'ISR', 'Israel', '', 'High income', 'Middle East & North Africa', NULL),
	('IT', 'ITA', 'Italy', '', 'High income', 'Europe & Central Asia', NULL),
	('JM', 'JAM', 'Jamaica', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('JP', 'JPN', 'Japan', '', 'High income', 'East Asia & Pacific', NULL),
	('JE', 'JEY', 'Jersey', '', '', '', NULL),
	('JO', 'JOR', 'Jordan', '', 'Upper middle income', 'Middle East & North Africa', NULL),
	('KZ', 'KAZ', 'Kazakhstan', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('KE', 'KEN', 'Kenya', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('KI', 'KIR', 'Kiribati', 'LDC', 'Lower middle income', 'East Asia & Pacific', 'Y'),
	('KW', 'KWT', 'Kuwait', '', 'High income', 'Middle East & North Africa', NULL),
	('KG', 'KGZ', 'Kyrgyzstan', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('LA', 'LAO', 'Lao People\'s Democratic Republic', 'LDC', 'Lower middle income', 'East Asia & Pacific', NULL),
	('LV', 'LVA', 'Latvia', '', 'High income', 'Europe & Central Asia', NULL),
	('LB', 'LBN', 'Lebanon', '', 'Upper middle income', 'Middle East & North Africa', 'Y'),
	('LS', 'LSO', 'Lesotho', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('LR', 'LBR', 'Liberia', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('LY', 'LBY', 'Libya', '', 'Upper middle income', 'Middle East & North Africa', 'Y'),
	('LI', 'LIE', 'Liechtenstein', '', 'High income', 'Europe & Central Asia', NULL),
	('LT', 'LTU', 'Lithuania', '', 'High income', 'Europe & Central Asia', NULL),
	('LU', 'LUX', 'Luxembourg', '', 'High income', 'Europe & Central Asia', NULL),
	('MG', 'MDG', 'Madagascar', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('MW', 'MWI', 'Malawi', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('MY', 'MYS', 'Malaysia', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('MV', 'MDV', 'Maldives', '', 'Upper middle income', 'South Asia', NULL),
	('ML', 'MLI', 'Mali', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('MT', 'MLT', 'Malta', '', 'High income', 'Middle East & North Africa', NULL),
	('MH', 'MHL', 'Marshall Islands', '', 'Upper middle income', 'East Asia & Pacific', 'Y'),
	('MQ', 'MTQ', 'Martinique', '', '', '', NULL),
	('MR', 'MRT', 'Mauritania', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('MU', 'MUS', 'Mauritius', '', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('YT', 'MYT', 'Mayotte', '', '', '', NULL),
	('MX', 'MEX', 'Mexico', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('FM', 'FSM', 'Micronesia (Federated States of)', '', 'Lower middle income', 'East Asia & Pacific', 'Y'),
	('MC', 'MCO', 'Monaco', '', 'High income', 'Europe & Central Asia', NULL),
	('MN', 'MNG', 'Mongolia', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('ME', 'MNE', 'Montenegro', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('MS', 'MSR', 'Montserrat', '', '', '', NULL),
	('MA', 'MAR', 'Morocco', '', 'Lower middle income', 'Middle East & North Africa', NULL),
	('MZ', 'MOZ', 'Mozambique', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('MM', 'MMR', 'Myanmar', 'LDC', 'Lower middle income', 'East Asia & Pacific', 'Y'),
	('NA', 'NAM', 'Namibia', '', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('NR', 'NRU', 'Nauru', '', '', '', NULL),
	('NP', 'NPL', 'Nepal', 'LDC', 'Low income', 'South Asia', NULL),
	('NL', 'NLD', 'Netherlands', '', 'High income', 'Europe & Central Asia', NULL),
	('NC', 'NCL', 'New Caledonia', '', 'High income', 'East Asia & Pacific', NULL),
	('NZ', 'NZL', 'New Zealand', '', 'High income', 'East Asia & Pacific', NULL),
	('NI', 'NIC', 'Nicaragua', '', 'Lower middle income', 'Latin America & Caribbean', NULL),
	('NE', 'NER', 'Niger', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('NG', 'NGA', 'Nigeria', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('NU', 'NIU', 'Niue', '', '', '', NULL),
	('NF', 'NFK', 'Norfolk Island', '', '', '', NULL),
	('MP', 'MNP', 'Northern Mariana Islands', '', 'High income', 'East Asia & Pacific', NULL),
	('NO', 'NOR', 'Norway', '', 'High income', 'Europe & Central Asia', NULL),
	('PS', 'PSE', 'Occupied Palestinian Territory', '', '', '', 'Y'),
	('OM', 'OMN', 'Oman', '', 'High income', 'Middle East & North Africa', NULL),
	('PK', 'PAK', 'Pakistan', '', 'Lower middle income', 'South Asia', NULL),
	('PW', 'PLW', 'Palau', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('PA', 'PAN', 'Panama', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('PG', 'PNG', 'Papua New Guinea', '', 'Lower middle income', 'East Asia & Pacific', 'Y'),
	('PY', 'PRY', 'Paraguay', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('PE', 'PER', 'Peru', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('PH', 'PHL', 'Philippines', '', 'Lower middle income', 'East Asia & Pacific', NULL),
	('PN', 'PCN', 'Pitcairn', '', '', '', NULL),
	('PL', 'POL', 'Poland', '', 'High income', 'Europe & Central Asia', NULL),
	('PT', 'PRT', 'Portugal', '', 'High income', 'Europe & Central Asia', NULL),
	('PR', 'PRI', 'Puerto Rico', '', 'High income', 'Latin America & Caribbean', NULL),
	('QA', 'QAT', 'Qatar', '', 'High income', 'Middle East & North Africa', NULL),
	('KR', 'KOR', 'Republic of Korea', '', 'High income', 'East Asia & Pacific', NULL),
	('MD', 'MDA', 'Republic of Moldova', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('RE', 'REU', 'Reunion', '', '', '', NULL),
	('RO', 'ROU', 'Romania', '', '', '', NULL),
	('RU', 'RUS', 'Russian Federation', '', 'High income', 'Europe & Central Asia', NULL),
	('RW', 'RWA', 'Rwanda', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('BL', 'BLM', 'Saint-Bartholemy', '', '', '', NULL),
	('SH', 'SHN', 'Saint Helena', '', '', '', NULL),
	('KN', 'KNA', 'Saint Kitts and Nevis', '', 'High income', 'Latin America & Caribbean', NULL),
	('LC', 'LCA', 'Saint Lucia', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('MF', 'MAF', 'Saint-Martin (French part)', '', 'High income', 'Latin America & Caribbean', NULL),
	('PM', 'SPM', 'Saint Pierre and Miquelon', '', '', '', NULL),
	('VC', 'VCT', 'Saint Vincent and the Grenadines', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('WS', 'WSM', 'Samoa', 'LDC', 'Lower middle income', 'East Asia & Pacific', NULL),
	('SM', 'SMR', 'San Marino', '', 'High income', 'Europe & Central Asia', NULL),
	('ST', 'STP', 'Sao Tome and Principe', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('SA', 'SAU', 'Saudi Arabia', '', 'High income', 'Middle East & North Africa', NULL),
	('SN', 'SEN', 'Senegal', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('RS', 'SRB', 'Serbia', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('SC', 'SYC', 'Seychelles', '', 'High income', 'Sub-Saharan Africa', NULL),
	('SL', 'SLE', 'Sierra Leone', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('SG', 'SGP', 'Singapore', '', 'High income', 'East Asia & Pacific', NULL),
	('SX', 'SXM', 'Sint Maarten (Dutch part)', '', 'High income', 'Latin America & Caribbean', NULL),
	('SK', 'SVK', 'Slovakia', '', 'High income', 'Europe & Central Asia', NULL),
	('SI', 'SVN', 'Slovenia', '', 'High income', 'Europe & Central Asia', NULL),
	('SB', 'SLB', 'Solomon Islands', 'LDC', 'Lower middle income', 'East Asia & Pacific', 'Y'),
	('SO', 'SOM', 'Somalia', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('ZA', 'ZAF', 'South Africa', '', 'Upper middle income', 'Sub-Saharan Africa', NULL),
	('SS', 'SSD', 'South Sudan', '', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('ES', 'ESP', 'Spain', '', 'High income', 'Europe & Central Asia', NULL),
	('LK', 'LKA', 'Sri Lanka', '', 'Lower middle income', 'South Asia', NULL),
	('SD', 'SDN', 'Sudan', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', 'Y'),
	('SR', 'SUR', 'Suriname', '', 'Upper middle income', 'Latin America & Caribbean', NULL),
	('SJ', 'SJM', 'Svalbard and Jan Mayen Islands', '', '', '', NULL),
	('SZ', 'SWZ', 'Swaziland', '', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('SE', 'SWE', 'Sweden', '', 'High income', 'Europe & Central Asia', NULL),
	('CH', 'CHE', 'Switzerland', '', 'High income', 'Europe & Central Asia', NULL),
	('SY', 'SYR', 'Syrian Arab Republic', '', 'Lower middle income', 'Middle East & North Africa', 'Y'),
	('TJ', 'TJK', 'Tajikistan', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('TH', 'THA', 'Thailand', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('MK', 'MKD', 'The former Yugoslav Republic of Macedonia', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('TL', 'TLS', 'Timor-Leste', 'LDC', '', '', NULL),
	('TG', 'TGO', 'Togo', 'LDC', 'Low income', 'Sub-Saharan Africa', 'Y'),
	('TK', 'TKL', 'Tokelau', '', '', '', NULL),
	('TO', 'TON', 'Tonga', '', 'Upper middle income', 'East Asia & Pacific', NULL),
	('TT', 'TTO', 'Trinidad and Tobago', '', 'High income', 'Latin America & Caribbean', NULL),
	('TN', 'TUN', 'Tunisia', '', 'Upper middle income', 'Middle East & North Africa', NULL),
	('TR', 'TUR', 'Turkey', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('TM', 'TKM', 'Turkmenistan', '', 'Upper middle income', 'Europe & Central Asia', NULL),
	('TC', 'TCA', 'Turks and Caicos Islands', '', 'High income', 'Latin America & Caribbean', NULL),
	('TV', 'TUV', 'Tuvalu', 'LDC', 'Upper middle income', 'East Asia & Pacific', 'Y'),
	('UG', 'UGA', 'Uganda', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('UA', 'UKR', 'Ukraine', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('AE', 'ARE', 'United Arab Emirates', '', 'High income', 'Middle East & North Africa', NULL),
	('GB', 'GBR', 'United Kingdom of Great Britain and Northern Irela', '', 'High income', 'Europe & Central Asia', NULL),
	('TZ', 'TZA', 'United Republic of Tanzania', 'LDC', 'Low income', 'Sub-Saharan Africa', NULL),
	('US', 'USA', 'United States of America', '', 'High income', 'North America', NULL),
	('VI', 'VIR', 'United States Virgin Islands', '', 'High income', 'Latin America & Caribbean', NULL),
	('UY', 'URY', 'Uruguay', '', 'High income', 'Latin America & Caribbean', NULL),
	('UZ', 'UZB', 'Uzbekistan', '', 'Lower middle income', 'Europe & Central Asia', NULL),
	('VU', 'VUT', 'Vanuatu', 'LDC', 'Lower middle income', 'East Asia & Pacific', NULL),
	('VE', 'VEN', 'Venezuela (Bolivarian Republic of)', '', 'High income', 'Latin America & Caribbean', NULL),
	('VN', 'VNM', 'Viet Nam', '', 'Lower middle income', 'East Asia & Pacific', NULL),
	('WF', 'WLF', 'Wallis and Futuna Islands', '', '', '', NULL),
	('EH', 'ESH', 'Western Sahara', '', '', '', NULL),
	('YE', 'YEM', 'Yemen', 'LDC', 'Lower middle income', 'Middle East & North Africa', 'Y'),
	('ZM', 'ZMB', 'Zambia', 'LDC', 'Lower middle income', 'Sub-Saharan Africa', NULL),
	('ZW', 'ZWE', 'Zimbabwe', '', 'Low income', 'Sub-Saharan Africa', 'Y');
/*!40000 ALTER TABLE `ref-country-classification` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
